[workspace]
resolver = "2"
members = [
    "crates/oryn-common",
    "crates/oryn-engine",
    "crates/oryn-scanner",
    "crates/oryn-e",
    "crates/oryn-h",
    "crates/oryn-r",
    "crates/oryn",
]
